### ISSUE TITLE
uhh where is brv.dll

### ISSUE THREAD

**Issue by DaRK72RU** [KoT3isGood/libbrv#1]
I cant find it. May it be because i've built this thing with .sh file?

**Comment by DaRK72RU** [comment]
![image](https://github.com/user-attachments/assets/2bbef852-f240-4e49-a52c-6627c9640bc4)

**Comment by DaRK72RU** [comment]
this is happening when im doing build.sh file

**Comment by KoT3isGood** [comment]
Read README once again
